<template>
  <Day :day="5" :solutions="solutions" :taskInput="taskInput" @input-changed="onInputChanged">
  </Day>
</template>

<script>
import Day from '@/components/Day'

export default {
  components: {
    Day
  },
  data: function () {
    return {
      taskInput: 'BBFFBFBRLL\nFFFFBFBRLR\nBFFBBFBRLR\nBFBBBFBLLL\nFFBBFBBLRR\nBFBFFFFRRL\nBBBBFFFRLR\nBFFFBBFRLL\nFFFFBFBRRL\nBFBBFFFRRL\nBBFBBBFRLL\nFBFFBFFRLL\nFBBBBBBLRL\nFFFBBFBLRL\nFFBBFFFLLR\nFBBFFFBLLL\nFFBFBBBRRL\nFBFBBBFRRL\nFFBBBFFLRL\nBFBBBBFRLR\nFBBBFFBRRL\nFBBFBFFRLL\nFBFBFBBLLL\nBFBFFFFLRR\nFFFBBFFLLL\nFFFFBFFRLL\nFBBBBFBRRR\nFBBFBBBLRL\nBBBBFFFLLL\nFFFFBFBLLR\nBFFFFBBRLL\nBFFFFBBRLR\nBFFFFFBRLL\nBFFBBBFRRL\nFBFFBBBLRR\nBFBFFBFRRR\nBBBBFFBLRR\nFFFFFBBRLR\nBFFFBBBRLR\nBBFBFFBRRL\nFBBFBFBLRR\nBFBBFBFRLR\nFFFFFBFRRR\nBFFFFFBLRL\nFFFBFBBLLR\nBFFFBBBLRR\nFFBFFBBRRL\nFBBBBBBLLL\nFBBBBFBLRL\nBBFFFBFRRL\nBBFFFBBRRL\nFFBFBFBLRL\nFFFFBBBRLR\nFBBFFBFLRL\nFBBBBFBRLR\nBBFBFBBLRL\nBBBBFFFLRR\nBFBBFFBRLL\nBFBBFBBRLR\nFFFBBFBRRR\nBFFBBBFRRR\nBFBBFBBLRR\nFBBFFBBLRL\nFFFBFBBRRL\nBFFFBFBRRR\nFBBBFFBLRR\nBBFFBBBLLR\nBFFBBBBRLR\nBBBBFBFRRR\nBBBBFFFRRL\nBBFFBBBRRL\nFFBBBBBRRL\nFFFFBBFRRL\nBFFFFFBLLL\nFFBFFBBLRL\nFFFBBFFLRL\nBFBFBFFLLR\nFFFFBFFRRL\nFBBBBFFRLR\nFBBBBFBRRL\nFBBBFBFLLR\nFBBBBBBRRR\nFBBFFFFRRL\nFBFBFFFRLL\nBBFFFBFRLL\nBFFBFFFRLL\nFFFFBFFLRL\nFBBFFFFLLR\nBBBBFFBRLL\nFBFBFBBRLL\nBBFBBBFLLL\nFFBFBBBRRR\nBFBBFBFRRR\nBFBFBBFLRR\nBBFBBBFLRL\nBBFFFBBLRL\nFBFFFBFRLR\nFFBFFBBRLL\nFFBFFBFRLR\nBBBFBFFLLR\nBBFBFBBLRR\nFBBBBFFLLR\nBFFBFBFLRL\nFFFBFFFLRR\nFBBFBBBRRL\nFBFBBBBRRL\nBFBFBBFLLL\nBFBFBBFRLL\nFBFBFFBLLR\nFBFFFFBRLR\nBBFBBBFRRL\nBBBFFFFLLL\nFFFFBFBLRL\nFFBFFFBLLR\nFFFBBBBRRL\nFFBFFFBLRL\nBBBBFBFRRL\nFFFBFFFLLR\nBBBBFBBRLR\nBBFBBBBRRL\nFBFBFFBRLL\nFBBBFBFRLL\nBFFBFBBRLR\nFBFBFBBLRR\nFBBFFFBLRR\nFFFBBFFRLR\nBBBFFFBRLR\nBBFFBFFLLL\nBFFFFBBLLR\nBFBFBBFLRL\nFFBFBFBRLL\nFBBFBFBRRL\nBBBFBFFLLL\nFFBBFFFRRR\nBFFBBFBLLL\nBBBFFBFLLR\nFFFBFBBLLL\nFFBFBFFRLL\nBFFBBBBLRL\nFBFBBFFLRL\nFBFFBFBLRL\nBFBBBBFLRR\nBBBFBFFRRR\nFBFBBFFRLR\nBFBBFFFLLR\nBFFFBFBLRR\nFBFBFBBRLR\nFFFFFBFRLR\nFFFFBBBRRL\nFBBFFBFLLL\nFBBBBBBRLR\nFBBFFFBRLR\nFBBBFBBRLL\nFFFBFBFRLL\nBFBFBBFLLR\nFFBFFBFRRL\nBBFBBBFRLR\nFFBBBBBLRL\nBBFBBFBRLL\nFFBFFFBRLL\nFFBBBFFRLR\nBFFBBBFLRL\nFFBFBFBRRL\nFBBFFFBRRR\nBBFBBFFLLL\nFBFFFFFRLL\nFBFFFFBLRL\nFFFBFFBRRR\nBBBFBFBRLL\nBBBBFBBRLL\nBFFBFBBLLR\nBBBFFFBLRL\nBFFBFFBRLL\nBFFBBFBRRL\nFBFFFFFRRL\nFFBBFBBRRR\nBBFFBBFLLR\nFFBFFBBLRR\nBBBFBFFLRL\nBBBBBFFLLL\nFFBBBBBLRR\nBFFBFFBRLR\nBFFBBFBLRL\nBBFFBBFRRL\nFFFBFFBRLR\nBFBFBBBLLR\nBFFBFFFLLL\nFBBFBBBRLR\nBFBFBBBRRL\nFBFBFFBRRL\nBBBFBFBLRL\nBFFFBBBLLR\nFBBBFBFLRR\nFFBBBBBRLR\nFFBFFBBLLL\nBBFFBFBLRL\nBFBFBFBRRL\nBFBFFBFLRR\nFFBBBFBLLR\nBFBFBBBRRR\nFBFFBBFLRR\nBBBFBFFRLR\nBFFFFBFRLL\nFFFFBBFLRL\nFBBBBFBLLR\nBFBFFFFLLR\nFFBBFBBRLL\nFBFBBFFRRL\nBFFFBBFLRR\nBBBFFBFLRR\nFBBBFFFLRR\nBBFFFBFRLR\nFFFBFBBRLR\nFFBBFBBLRL\nFBFFBBBRRR\nBBFBBBBLLR\nBFFFFFBRLR\nBBFBFBFRLR\nFBFBBBFLRR\nBBFFFBBLLL\nBBBFBFBLLR\nBFFBBFFLRL\nFFBFFFFRLR\nBFFFFFBRRR\nFFBBBFBLRR\nBBBFBBBLRR\nBBBBBFFLRL\nFBFFFBFRRR\nBFFFFFBLLR\nFFBBFBFLRL\nBBFFFBFRRR\nBBBFBFBRLR\nBBFBBFBLRL\nFFFBFFBLRL\nFFFBFFBRLL\nBBBBFFFRLL\nFBBFFFFLRR\nFFBBFFBLLR\nFBFFBFBRLL\nFFBFBFFLLL\nBFBBFFBLRR\nBFBFFFBRLR\nBBBFFBFRRL\nFFBBFBBRLR\nBBFFFFBRLL\nBBFFBFBLLR\nBBFFBFBRRL\nFBBBFBBRRL\nFFFFFBBRLL\nFBFFFBFRRL\nFBBFBFFLRL\nFBFBBBFRLL\nBFFFBFFLRR\nBFFBBFBRRR\nBFBBFBBLLL\nBBFBFFFLRL\nBFBFFFFRRR\nFBBFBBBLRR\nFFBBBBBLLR\nFFFFBBFRRR\nFFBBFFBRRR\nBBFFFBBLLR\nBFFBFFBLLR\nBBBFFFFRLL\nFFFBFBFLLR\nBBFBFFBLRL\nFFBBBFBRRL\nBBFBBBBRRR\nBBFBBFBRRR\nFFFFBFBRLL\nFFFBFFBLLR\nFFBFBBBLLR\nFBBBFBFLRL\nBFBBBBBLLL\nBFBBFBFRLL\nBFBFBBBLRR\nFFBFBFBLLL\nBFBFFFBLLR\nBBBBFBBRRL\nFFBFFBFLRR\nFBFBBFFLLL\nBFBFBBBRLL\nBFBFFFBRRR\nFBBFBBFRRR\nBFFBFBFRLL\nBBFFFFBRRL\nBFBFBFBLRL\nFBBBFFBRRR\nFFFFBBBLLR\nBBBFFFFRRR\nBBBFFFFLRR\nFFBFBBFLLL\nBFBFBFFRRR\nBBFFFBBRLR\nFBBBBBFLRR\nFBFFBFBLLR\nFFBFFFBLLL\nBFFFFBBLRL\nBBBFBBBRRR\nBBBFFFBRRL\nBFFFFBBLRR\nBBFFBBBRLL\nBFBFFFFLRL\nBBFFFFFLRR\nBBFFFBFLRR\nFBFFBBFRRL\nBFFFBBBLLL\nBFBBBFFRRL\nBFFFBFBLRL\nFBBBBFFRLL\nBFBFBBBLLL\nBFBBFFBLLR\nBBBBFBBLLL\nFBFBFBFLRR\nFBBBFFFRLR\nBFFBFBFRRL\nBFBBFFFRLR\nFBBBFFFLRL\nFBBBBFFLRR\nFBFFFFBLLL\nBBBFFBBRLL\nFBBFBFFLLL\nBFFBBFBRLL\nBFFFFBFRLR\nFFFBBFFRRR\nFFFBBBFRLR\nFBBFFBFRRR\nFBFFFFBRRR\nBFBFBFBRLL\nBBBBBFFRLL\nBFFFFBFLLL\nBBFFBBFRRR\nBFBFFFBLLL\nFFFBFBFRRR\nFBFBBFBRRL\nBFBFFFBRRL\nFFFBBBBRRR\nBFBFFBBLLR\nFBBBFBBLLR\nBBFBBFBLLR\nBFFFFFFLLL\nFBBFBFFRLR\nFFBBBBFLLL\nBFBBFBFLRL\nBFBFBFBLLL\nFBBBFBBLLL\nBFBFBFBRRR\nFBFBFFFLRR\nFBFBBFBLLL\nFBFFFFBLRR\nBBBFFBFRLL\nFFFBFFBRRL\nBBFBFBFRRR\nFBBFFBFRLL\nBBBFBBFRRR\nFBFBBFFLRR\nBBFBBBBLLL\nFFBFFBBLLR\nFBBBFFFRRR\nFFFFFBBLLL\nFBFFBBBRRL\nBFFBBBFRLL\nBFFFBFFLLR\nFBFFBBBLLL\nFFFBBBBRLR\nBFBBBFFLLR\nFBFBBBBLLR\nFBBFBFBRRR\nBBFFBFFRRR\nFBBFFFFLRL\nFBFBBBBLRR\nFFBBFBFRRR\nFBFBBFBRLR\nBBFBFBFRRL\nFBBBBBFLLL\nFBFFBFFLLR\nFBFBFBFLLL\nBFFBFBFLRR\nFBBBBBFRLL\nBFFBBBFRLR\nBBFFFFFLLL\nFFFFBBFRLR\nBFBBBBBLLR\nBBFFFBBRLL\nFBFFFFFLRR\nBBBFFBBRRR\nFFFBFFBLRR\nBFFFFFFRLL\nBBFFFBFLLR\nBFFBBFFLLL\nFBBBFFFRRL\nBBBBFBFLLL\nFBBFFFFRLL\nFBFBBFBRRR\nBFFFFFFRLR\nBFBFFFFLLL\nFBFBBFBLLR\nBFBBFBFLLR\nBFBBFBBLRL\nBFFFBFFRLR\nBBFBBFFRRR\nFBFBFBFRLL\nFFBBFBFRRL\nBFFFBFFLRL\nFBFFBBBLRL\nBBBFFBFLRL\nFFBBBFBRRR\nBFFFBFBRRL\nFFBBFBFLLR\nBFFBFFFLRL\nBBBFFFFLRL\nFFBBFFBRLR\nBFFBFBBRRR\nBFFBFFBLRR\nBFFFBBBLRL\nFFBFBFFRRR\nFFBFBBFRRL\nFFBBBBFRLR\nBBBFBBFLRR\nBFBBFFFLRL\nBFBBBBFRRR\nFFBFFFBLRR\nFFBFBFFLLR\nFBFFBFBRRL\nBFFFFFFLRR\nFBBBBBBLRR\nBBFFBBFLLL\nBFBBBBFRRL\nFFBFFFFLLR\nBBFFFBFLLL\nFFBFBFFLRR\nFFBBBBFLRL\nFFFBBBFRRR\nFBBFFBFLRR\nFBFBBBBRLL\nFFFBBBBLLL\nFFBBBBFRRL\nFBBBBBBLLR\nFBBFBFFLLR\nBFBBFBFRRL\nBBFFBFBLRR\nFBFFBFFRRR\nFFFBBBBRLL\nBFFFFFFLLR\nBFFFFBFLLR\nFFFBBBFRRL\nBFFBFFFLLR\nFBFFFFFLLL\nBBBBFBBLRR\nBBFFBFFRRL\nBFBBFFBLRL\nFBBBBFFRRR\nFFFBBFBLLR\nFBBFFFFRLR\nFFFBFBBLRL\nBFBBBBFLLR\nBBFFFBBRRR\nBFBFBBFRRR\nFFFBFFFRRL\nBBFBFBFRLL\nFBFFBFFRLR\nBFFBFFBLLL\nFFFFBFBRRR\nBFFBBFFRLR\nFBBBFBBLRL\nFBFFBBBRLL\nFBBBBBFRLR\nFBBBFFBLLR\nFBFBBFFRLL\nFFBBBFFRRL\nBBFBBBBLRR\nBFFFFBBRRL\nBFFFBFFRRL\nFBBFBBFRRL\nBFBBFFBRLR\nBFFFFBFLRL\nBBFFFFBLLR\nFBFFFFFRRR\nFFFFBBBRLL\nFFFFBBFLLR\nBBBFBBBLLR\nFFBFFFFRLL\nFBBBFFFLLR\nFFFFBBBLRL\nFBFBBBFLLL\nFBFFFBFLLL\nBBBFFBBLRR\nFBBBFFFLLL\nBBFBBFFRLR\nFFFFBFFLLL\nBBFFBFFLLR\nBFBBBBFRLL\nBFFBBFFRLL\nBBFFFFBRLR\nFBBBBFBRLL\nBFBBFFBLLL\nFBBFFFFLLL\nFFBFFBBRRR\nFBFFBBBLLR\nBFBBBFBLRL\nBBFFBBFRLR\nFFBBBFFRRR\nBBBBFBFRLL\nBFFFBBBRRR\nBBFFFFFRLR\nFBFBFFFLLR\nBBFFBBFRLL\nBFFBBFFLLR\nFFFFBBBRRR\nFFFBFBFRRL\nBBBFBBFRRL\nFBBBFBBRLR\nFBFBFFFRRR\nBFFBBBBLLR\nBBBFBFBLRR\nFBFBBFBLRR\nBBBFFBBRLR\nFBFBFBBLRL\nBBBFFBBLLR\nBBFBFBBRLL\nFBBBFFBRLL\nFFBBFFFRLL\nFBFFBFFRRL\nBBBBFFBRRR\nFBFBFFFLLL\nFFFFBBFRLL\nBFFBFFFRRR\nBBFFBFBRLR\nFFBBBFBRLL\nBBFBFFFLLL\nFBBFBBFRLR\nFFFBFFFRLL\nFBBFFBFRRL\nBFBFFBFLRL\nBBBFFFFRRL\nBBFFBBBRRR\nFFBFBFFRLR\nFFBBFFFRLR\nFBFBFBBRRL\nFFBBFBBLLR\nFBFFFFFRLR\nBBBBFBBLRL\nBBFFBFFRLL\nFBBBFBFLLL\nBBBFBFBLLL\nBFFBFFFLRR\nBFBFFBFRLL\nBFBBBBFLRL\nBBBBFFFLRL\nFFFBFFBLLL\nFFFFBFBLRR\nFFFFFBBRRR\nFFFBFBBLRR\nBFFFBBFRRL\nFFBFBBFLRR\nBBFBBBBRLL\nFBBBBBFRRR\nBFFFFBFLRR\nBFBFFBBRRL\nFBFBBFBLRL\nBBBFFBBLLL\nFFBBBFFLRR\nBBBBFBFLRL\nBBBBFFBLLL\nBFFFBBBRLL\nFBBFFFBLLR\nBFBBBFFRLL\nFBBFFBFRLR\nBBFBBFBRRL\nBFBBFBBRLL\nBBFBFFFRRR\nFBBBFFBRLR\nBBFFBBBLLL\nBFFFBFBLLR\nBBFBFFBRLR\nFFBFFFBRRL\nFFBFBFBRLR\nBBFFBFBLLL\nBFBFBBBRLR\nFBFFFBFLRL\nBFBFFFFRLR\nBBFFFFFRLL\nBBBFFFBRRR\nFBFFBBFRRR\nFFFBBFFLLR\nFFFBFBFRLR\nFFBBBBFLRR\nBFFFBFBRLR\nFFBFFBBRLR\nFBBFFFBRLL\nFBBFBFFLRR\nBFFFFFFRRR\nBBBFBBBRLL\nFBFFFBBRRL\nFFBBBFBLRL\nFBFFBFBLLL\nFFFFBFFRLR\nFBFFBFFLRL\nFFBFBFFRRL\nFBBBFFBLLL\nBFFFFBBRRR\nBBBBFFBLLR\nFFFFFBBLRL\nFFBBBFFLLR\nFBBBFFFRLL\nFFBFFBFRRR\nBBBBFFBRLR\nFFBBFBFLRR\nBFBBBBBRLL\nBFBBBBBLRL\nFFBFBBFRLR\nFFBFBBBRLL\nBFFBBFBLLR\nBFBFFFFRLL\nBBFBBFFRRL\nBFBFFBFRLR\nFFBBFFFLRL\nFFBBBFFLLL\nBFFBFBFLLL\nBFBFBFBRLR\nFBBFBFBLLR\nBFBFFBBLRR\nFFFFBFFLRR\nBBFBBFBLLL\nFBFFFFFLRL\nBBBBFBFRLR\nBFFFBBFRRR\nBBFBBFFLRR\nBFBBBFBRLL\nBFFBFFBLRL\nBFBFFFBLRR\nBFFFBFFRRR\nFBFFFBBLLL\nFBFBBBBLRL\nFBFBFFFRLR\nBBFFBBFLRL\nBFBFBFBLLR\nFBFFFBFLRR\nBFFBFBBRRL\nFBFBBBFLLR\nFBFBFFBLRL\nBBFBFBBRRR\nFBBFFBBLRR\nBBFFFFBLLL\nFBFFBBBRLR\nFBFFFBFLLR\nBFBBFFFLLL\nBBBBFBFLRR\nBFFBFBBRLL\nBFFFFFFRRL\nBFBFBFFRRL\nFFBFBFBLRR\nFFFBFBFLRR\nFFFBFBBRRR\nFBFFFBBRLR\nFFBBFFBRRL\nBBFBBBBRLR\nFFFBBFBRLR\nFBFFBBFLRL\nBBBFFFBRLL\nBBBFBBBRLR\nFFBFFFFRRR\nFBBFBFBLLL\nBFBBBFBRRR\nBFBBFFBRRL\nFFFBBBFLLL\nFBBBBFBLLL\nFFBFBFBLLR\nBFFBFFFRLR\nBBBBFBFLLR\nFBBFBBFLLL\nFBFFFBBLRR\nFFBFBBFRRR\nFBFBFBBRRR\nFFBFBFBRRR\nFFBBFBFRLL\nFBFBBBBLLL\nBFBFFBBLLL\nBBBFFFFRLR\nBBBFBFBRRR\nBFBFBFBLRR\nBFBFBBFRLR\nBFBBBFFLLL\nFBBFFBBRRR\nBFFFFFBLRR\nBFFBFBFRLR\nBBFFBFFRLR\nBFBBBBBLRR\nFBFFFBBLRL\nBFFBFBFRRR\nBFFFFBFRRL\nFFBFBBBLLL\nFBBBFBFRLR\nFFFBBFBLLL\nFBFBBBFRLR\nBFBFFFBRLL\nBFFBBBBLRR\nBBFFBFFLRL\nBBBFBBFRLL\nBBBFFFBLRR\nFBBFFBBRLR\nFBBFBBFLRR\nBBFBFBBRRL\nFFBBBBBLLL\nBFBBFBBLLR\nBFBBBFFLRR\nBBBFFFBLLL\nFBFBBBBRLR\nFBFBFFBLRR\nFFFBBBFLRL\nBBBFFBBLRL\nFBBFBFBRLL\nBBBBFBBLLR\nFFBBBBBRRR\nBBBFBBFLRL\nBFBBBFBRLR\nFFFBFFFRRR\nBFFFBBFRLR\nFBFFFFBRLL\nBFFBFFBRRL\nBBBFBBBRRL\nFFBFFBFRLL\nFBFBBFFRRR\nFFBFFFBRLR\nFFFFBFFLLR\nFFBBFFFLLL\nFBFFFBBLLR\nFFBFBBFLRL\nBFFBFBBLLL\nFBBBFBBLRR\nFFFBFBFLLL\nFBBFBFBLRL\nFFBBFFFRRL\nBFBFBFFRLL\nBFFFFBFRRR\nBBBBFFFRRR\nBFFBFFBRRR\nFFFFBFFRRR\nFFBBFBBRRL\nFBBFBBBRLL\nBBBBFFBLRL\nFBBFBBFRLL\nBFFBBBBRLL\nBFBBBFBRRL\nBBFBFBFLLR\nFFFBBBBLLR\nBFFBBFFLRR\nBBBFBBBLRL\nFBBFBFFRRL\nBBFBFFFRRL\nBBFBFFBLRR\nBBBFBBFRLR\nFBBBFBFRRR\nBBFBFBFLRL\nFBBFBBFLRL\nFFBFFFFLRR\nBFBBFBBRRL\nFBBBBFFRRL\nFBFBFFBRRR\nBBBFFBFLLL\nFFFBFFFLRL\nFBFBBBFRRR\nBBBFBFFRRL\nBFBFFFBLRL\nBBBFBFFLRR\nBFFFBFFLLL\nFFBFBBFLLR\nFFBFBBFRLL\nFBFBBBFLRL\nBFFBBBBRRL\nFBBBFBFRRL\nFFBBBFBLLL\nBFBBBFFLRL\nBBBBBFFLLR\nFBFBFFFRRL\nBFFBFBBLRR\nBBFFFFBLRR\nFBFFBFBLRR\nFBFFBBFRLR\nFFBBFFBLRL\nFFFFFBBLRR\nBBBBBFFLRR\nBFBBBBFLLL\nFBBFBFFRRR\nFFFFFBBLLR\nFFBFFBFLLL\nFFBFBBBLRR\nFFBBFBFRLR\nBFBBBFFRRR\nFBFFBFBRLR\nBBBFBBFLLR\nBFBBFBFLRR\nFBBBFFBLRL\nBFBBBBBRLR\nFBBFBBFLLR\nBFBBBFFRLR\nFBBBBBFLRL\nBFBBBBBRRR\nBFFBBBBRRR\nBBFBFBFLRR\nBFFBBBBLLL\nBBFFFBFLRL\nBFBBFBFLLL\nFBFFFFBRRL\nFFBBBBFRRR\nFFBFBBBRLR\nBBFBFBFLLL\nFBFFBFBRRR\nFFFBBBFLLR\nFFFBFBFLRL\nBFBFBBBLRL\nFBBFFBBLLL\nBBBFBFBRRL\nFBFFFBBRRR\nBFFFBFBLLL\nFFFFBFBLLL\nFFFBBFBRLL\nFBBFFFBRRL\nFFBBFBFLLL\nFFBBFFBRLL\nFBFBFBFLLR\nBBFFFFBLRL\nBFBFBBFRRL\nFFFBFBBRLL\nFBBFFBBRLL\nBBFBFBBLLR\nBFFFBFFRLL\nBFBFBFFLRR\nFBFFFFBLLR\nFFFBBFBRRL\nFFFBBBBLRL\nFFBBFFBLRR\nBFFFBBFLLL\nFFFBFFFLLL\nFBFBFBFRRR\nBFBBBFBLLR\nBFFBFFFRRL\nFFFFBBFLRR\nFBFBFBFRRL\nBFBBFBBRRR\nBFBFFBBLRL\nFBFBBFBRLL\nFBBBBFFLRL\nFFBFBFFLRL\nFBBFBBBRRR\nFBFBFBFRLR\nFFBFFFFLRL\nBBFBFBBRLR\nBFBFFBBRLL\nBBFFBFBRRR\nBFBBBBBRRL\nBBFBBBFLLR\nBBFFBBBRLR\nBBFBFFFLLR\nFFFFBBFLLL\nFBBFFFFRRR\nBBFBFFBRLL\nFFBBFBBLLL\nBFBBFFFRRR\nBFBBFFFRLL\nBFFBBFFRRL\nBBFBBBFRRR\nBFFFBFBRLL\nBFFFBBBRRL\nFBFBBFFLLR\nFBFFBBFRLL\nBBFBBFBLRR\nBBBFFFFLLR\nFBBFBBBLLL\nFBFFBBFLLL\nBFFBFBBLRL\nBBFFFFFRRL\nFFBBBBBRLL\nFBFFBFFLLL\nFFFFFBFRRL\nBBBBFFBRRL\nFBBFBFBRLR\nBBFBBFBRLR\nBFFBBFBLRR\nBFFFFBBLLL\nBBBBFBBRRR\nBBBFFFBLLR\nFFBFFFFLLL\nFBBFFBFLLR\nBBFFFFFLRL\nFFFFBBBLRR\nFBBBBFFLLL\nFFBBFFBLLL\nBBFBFFBRRR\nFBFBFBFLRL\nFFFBBBFLRR\nBFBBBFBLRR\nFBBBBBFLLR\nBBFFBBBLRL\nFFBFFBFLLR\nFFFBBBFRLL\nFBFFFBBRLL\nBFFBFBFLLR\nFFBBBFBRLR\nBBFFFBBLRR\nBFFFBBFLRL\nFFFBBFFLRR\nBBBFBBBLLL\nBBFBFFFRLL\nFFFBBFFRRL\nBFBBFFFLRR\nBBFFFFBRRR\nBBFFFFFLLR\nBBFBBBBLRL\nFFBFBBBLRL\nBBFFFFFRRR\nFBFBFFBLLL\nBFFBBBFLRR\nFFFFFBBRRL\nBFFFFFBRRL\nBBBFBFFRLL\nFBFFBBFLLR\nBBBFFBFRRR\nBBFBFFFLRR\nBBFFBBFLRR\nBFBFFBFRRL\nFBBBFBBRRR\nBBFFBFFLRR\nBBFBFFFRLR\nFBBBBBFRRL\nBFFFBBFLLR\nBBFBBFFLLR\nFBFFFFFLLR\nFFFBBFFRLL\nBBFBBFFRLL\nFFFFBBBLLL\nBFBFFBBRLR\nFBBFBBBLLR\nBFFBBBFLLR\nBFFFFFFLRL\nBFFBBBFLLL\nBFBFFBFLLL\nBBFBFFBLLL\nFFBBBBFRLL\nFBFFBFFLRR\nBBBFFBBRRL\nBFFBBFFRRR\nBBBBFFFLLR\nBFBBFFBRRR\nFBFFFBFRLL\nFFBBBFFRLL\nFBBBBFBLRR\nFFFBBFBLRR\nFFBBFFFLRR\nBBFBBBFLRR\nFBFBFFBRLR\nFBBFFBBLLR\nBBFFBBBLRR\nBBFBFFBLLR\nFBBFFFBLRL\nBFBFBFFLRL\nFFFBFFFRLR\nFBFBFFFLRL\nBBBFFBFRLR\nBBBFBBFLLL\nFBFBFBBLLR\nBFBFBFFLLL\nFFBFFFBRRR\nBFBFBFFRLR\nFFFBBBBLRR\nBBFBBFFLRL\nFFBFFFFRRL\nBFBFFBFLLR\nFFBBBBFLLR\nFBFBBBBRRR\nFFBFFBFLRL\nFBBBBBBRLL\nBBFBFBBLLL\nFBBFFBBRRL\nFBBBBBBRRL',
      solutions: {
        partOne: null,
        partTwo: null
      },
      bflr: {
        B: (cur, i) => { cur.f += Math.pow(2, i) },
        F: (cur, i) => { cur.b -= Math.pow(2, i) },
        L: (cur, i) => { cur.r -= Math.pow(2, i) },
        R: (cur, i) => { cur.l += Math.pow(2, i) }
      },
      lr: {

      },
      parsedInput: null
    }
  },
  methods: {
    onInputChanged: function (input) {
      this.parsedInput = input.map(i => i.split(''))

      this.solvePartOne()
      this.solvePartTwo()
    },
    solvePartOne: function () {
      // For each boarding pass
      this.seatIds = this.parsedInput.map(p => {
        // Start with the initial configuration
        const cur = { f: 0, b: 127, l: 0, r: 7 }

        // First, determine the row
        let exponent = 6
        // Go through the first 7 letters
        for (let letter = 0; letter < 7; letter++) {
          // Adjust according to the letter
          this.bflr[p[letter]](cur, exponent--)
        }

        // Then determine the column
        exponent = 2
        // Go through the remaining letters
        for (let letter = 7; letter < 10; letter++) {
          // Adjust according to the letter
          this.bflr[p[letter]](cur, exponent--)
        }

        // Get the seat it
        return cur.b * 8 + cur.l
      })

      // Get the maximum
      this.solutions.partOne = this.seatIds.reduce((a, b) => a > b ? a : b)
    },
    solvePartTwo: function (input) {
      // Get the first row that has tickets (skip the minimum row)
      const startRow = Math.floor(this.seatIds.reduce((a, b) => a < b ? a : b) / 8) + 1
      // Get the last row that has tickets (skip the maximum row)
      const endRow = Math.floor(this.solutions.partOne / 8) - 1

      // Iterate through the row in the range
      for (let row = startRow; row <= endRow; row++) {
        // Iterate through the columns
        for (let col = 0; col < 8; col++) {
          // Get the seat id
          const id = row * 8 + col

          // Check if the current seat id isn't in the list, but the neighbors are
          if (this.seatIds.indexOf(id) === -1 && this.seatIds.indexOf(id - 1) !== -1 && this.seatIds.indexOf(id + 1) !== -1) {
            this.solutions.partTwo = id
            return
          }
        }
      }
    }
  }
}
</script>

<style>

</style>
